name: Spark Auto Update

on:
  schedule:
    - cron: '0 14 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: true

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar Spark, IA y Librerías
        run: |
          python -m pip install --upgrade pip
          pip install pyspark pandas pyarrow requests scipy google-generativeai==0.7.2

      - name: Ejecutar Script de Spark e IA
        run: python update_spark.py
        env:
          BANXICO_TOKEN: ${{ secrets.BANXICO_TOKEN }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

      - name: Guardar cambios en el Repo
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Spark Robot"
          
          # 1. Agregamos TODO lo que generó el script de Python (Parquet y JSON)
          git add datos_anomalias.parquet noticias_contexto.json || echo "Archivos no encontrados"
          
          # 2. Hacemos un commit local para que Git esté tranquilo
          git commit -m "Datos generados por el robot" || echo "Sin cambios nuevos"
          
          # 3. Ahora sí, bajamos tus cambios y mezclamos
          git pull origin main --rebase
          
          # 4. Empujamos todo a GitHub
          git push origin main
          
