name: Pipeline Automático Spark e IA

on:
  workflow_dispatch: # Permite ejecutarlo manualmente desde la pestaña Actions
  schedule:
    - cron: '0 * * * *' # Se ejecuta solo cada medianoche (opcional)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar Java (Necesario para Spark)
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Instalar Librerías
        run: |
          python -m pip install --upgrade pip
          pip install pandas pyarrow pyspark requests huggingface_hub

      - name: Ejecutar Script de Spark e IA
        env:
          BANXICO_TOKEN: ${{ secrets.BANXICO_TOKEN }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }} # <--- ¡ESTA ES LA CLAVE!
        run: python update_spark.py

      - name: Guardar cambios en el Repo
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Spark Robot"
          
          # Agregamos los archivos si existen
          git add datos_anomalias.parquet noticias_contexto.json || echo "Sin archivos nuevos"
          
          # Hacemos commit y push forzado para evitar conflictos de historial
          git commit -m "Actualización automática: $(date)" || echo "Sin cambios para commitear"
          git push origin main --force

      - name: Enviar Alerta a Telegram
        run: |
                curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
                -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
                -d text="🚀 ¡Hola Ricardo! El pipeline de Spark terminó. Llama 3 ya analizó el dólar. 📊 Revisa tu App aquí: [https://mx-anomaly-detector-r9dzbqmczcahqbpzhwqyz2.streamlit.app/]"
